[build]
publish = "public"

[build.environment]
NODE_VERSION = "17.6.0"
HUGO_VERSION = "0.93.0"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.17.7"

[context.development]
command = "npm install && hugo --minify"

[context.development.environment]
HUGO_ENV = "development"

[context.deploy-preview]
command = "npm install && hugo --minify"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"

[[redirects]]
  from = "/:lang/*"
  to = "/:lang/404.html"
  status = 404

[[redirects]]
  from = "/*"
  to = "/en/404.html" # Replace the "en" to your default language code.
  # to = "/404.html" # Use it when a monolingual site or "defaultContentLanguageInSubdir" is disabled.
  status = 404
